### ISSUE TITLE
Waymo Inference has issues 'fvdb._Cpp.JaggedTensor' object has no attribute 'numpy

### ISSUE THREAD

**Issue by yshen47** [nv-tlabs/XCube#5]
I am able to run inference for shapenet without problem. But for waymo, the command below, it complains AttributeError: 'fvdb._Cpp.JaggedTensor' object has no attribute 'numpy'. I am wondering how to fix this issue. 

python inference/sample_waymo.py none --total_len 20 --batch_len 4 --ema --use_ddim --ddim_step 100 --extract_mesh

`
Traceback (most recent call last):
  File "/scratch/bczy/yshen47/MMCityGen/mmcitygen/third_parties/XCube/inference/sample_waymo.py", line 132, in <module>
    udf_mesh = field.extract_dual_mesh()
  File "/scratch/bczy/yshen47/MMCityGen/mmcitygen/third_parties/XCube/ext/nksr-cuda/nksr/fields/base_field.py", line 206, in extract_dual_mesh
    dual_c = self.texture_field.evaluate_f_bar(
  File "/scratch/bczy/yshen47/MMCityGen/mmcitygen/third_parties/XCube/ext/nksr-cuda/nksr/fields/base_field.py", line 114, in evaluate_f_bar
    f_chunk = self.evaluate_f(
  File "/scratch/bczy/yshen47/MMCityGen/mmcitygen/third_parties/XCube/ext/nksr-cuda/nksr/fields/pcnn_field.py", line 39, in evaluate_f
    _, idx = self.kdtree.query(xyz.detach().cpu().numpy())
AttributeError: 'fvdb._Cpp.JaggedTensor' object has no attribute 'numpy'
`

**Comment by xrenaa** [comment]
Hi, I just fix this issue. Could you try again?

**Comment by yshen47** [comment]
Thanks for the fast respond! Do I need to recompile fvdb after pulling?
